#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.60136349, 0.96603345],
       [0.27617597, 0.7360144 ],
       [0.68205516, 0.11875466]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([ 1.08262731, -0.25172554])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 92.81432401 124.68813144]
 [123.76172056 160.02688383]
 [129.96803036 189.30688459]
 [ 99.53331095 134.32622773]
 [116.8334625  145.37479122]
 [ 92.81432401 124.68813144]
 [123.76172056 160.02688383]
 [129.96803036 189.30688459]
 [ 99.53331095 134.32622773]
 [116.8334625  145.37479122]
 [ 92.81432401 124.68813144]
 [123.76172056 160.02688383]
 [129.96803036 189.30688459]
 [ 99.53331095 134.32622773]
 [116.8334625  145.37479122]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(2932.0390082102685, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 2932.0390082102685
 
 Epoch count: 1 
 Loss value: 2041.1896931000208
 
 Epoch count: 2 
 Loss value: 1460.1646168535442
 
 Epoch count: 3 
 Loss value: 1075.8425817655218
 
 Epoch count: 4 
 Loss value: 817.1029298295241
 
 Epoch count: 5 
 Loss value: 639.143599594669
 
 Epoch count: 6 
 Loss value: 513.6652632419328
 
 Epoch count: 7 
 Loss value: 422.72591027263957
 
 Epoch count: 8 
 Loss value: 354.8922184677551
 
 Epoch count: 9 
 Loss value: 302.82828636001454
 
 Epoch count: 10 
 Loss value: 261.7840125097321
 
 Epoch count: 11 
 Loss value: 228.6466755469572
 
 Epoch count: 12 
 Loss value: 201.34518842349686
 
 Epoch count: 13 
 Loss value: 178.4752808375304
 
 Epoch count: 14 
 Loss value: 159.0631536565778
 
 Epoch count: 15 
 Loss value: 142.41598916767413
 
 Epoch count: 16 
 Loss value: 128.0269982810383
 
 Epoch count: 17 
 Loss value: 115.51476156039621
 
 Epoch count: 18 
 Loss value: 104.5841785056222
 
 Epoch count: 19 
 Loss value: 